### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by Nak9009** [h4h13/paisa#2]
Add New categories button not working. 
type 'Null' is not a subtype of type 'Category' in type cast

**Comment by h4h13** [comment]
Will add validation

**Comment by Nak9009** [comment]
one more when im trying to test in account page while add new card is not yet to validate field(card holder name, account name ...). after add card success it wont show card in accounts.

**Comment by h4h13** [comment]
Yes before logic was when you add any expense then it will show up the account card
