### ISSUE TITLE
Ability to add photos 

### ISSUE THREAD

**Issue by Vikrant0-7** [h4h13/Paisa#254]
Currently one can enter amount spent, but it will be great to have features that one can attach photo of bill with that expense, so one can remember where they spent their money.

**Comment by zahidshaikh08** [comment]
It would be nice if we can attach a screenshot of the transaction so that we do not have to worry or think about it in the future.

**Comment by h4h13** [comment]
This would be considered for next development

**Comment by tahayparker** [comment]
Is this done? I don't see it in 6.0.8

**Comment by h4h13** [comment]
The problem for not doing  this is i want to keep back and restore simple by doing this we have to worry about images also hence i'm closing this for now
