### ISSUE TITLE
Feature Request: Add ability to add upcoming expenses

### ISSUE THREAD

**Issue by Celtaa** [h4h13/Paisa#322]
**Current Behavior**

The app only allows users to create expenses with a date in the past or present. There is a recurring feature that can be helpful in some upcoming expenses like rent and car payments, which usually are always the same value. But other expenses like utility bills are always different.

**Proposed Behaviour**

The proposed behaviour would allow users to create expenses with a date in the future. This would allow users to track their upcoming expenses and budget accordingly.

**Optional Behaviour**

An upcoming expense could be greyed out until the date of the expense 

Thank you for your time and consideration.

**Comment by h4h13** [comment]
This is done as recurring feature
