### ISSUE TITLE
Feature Request: Do not count transfers between accounts as income or expense

### ISSUE THREAD

**Issue by sky-brunoteixeira** [h4h13/Paisa#324]
I would like to request a feature that would allow me to exclude transfers between accounts from my income and expense reports. Currently, when I transfer money from one account to another, it is counted as both an income and an expense, which skews my reports.

This is especially important for "This Month" and overview graphs.

I believe that this feature would be a valuable addition to the project, as it would make it easier for users to track their finances accurately.

**Comment by amzon-ex** [comment]
I second this. While the math and logic works currently, I'd love to see transfers recorded as transfers and not bloating my income/expense records.

**Comment by bitcrafty** [comment]
This one is really needed. Otherwise, finalizing expenses requires additional data cleaning and calculations.

**Comment by xunafay** [comment]
I've created a PR that changes how transactions are registered (#418). The only issue is that this will only apply to new transfers. Old transfers are simply registered as an income transaction and a second expense transaction. If anyone has suggestions on how to retroactively apply the new logic to old transfer, I'd love to hear it.

**Comment by h4h13** [comment]
Hey, I think I have fixed this issue closing for now let me know once the v6.2.3 releases
