### ISSUE TITLE
transaction input not using the correct decimator

### ISSUE THREAD

**Issue by DriesdeKort** [h4h13/Paisa#392]
I use the app with EUR Euro €.
The balances are correctly displayed. They use a comma ( , ) as a decimator. But when i put in a new transaction, i need to use the dot ( .) as a decimator. This is annoying and can cause wrong input amounts.
Thanks in advance for looking at this issue. Love the app!

Here you can see that EUR uses the comma as a decimator, which is correct. 
![Screenshot_20231122-221730_Fennec](https://github.com/RetroMusicPlayer/Paisa/assets/48886241/1323d433-02fd-483d-b016-0f761e8a199b)

**Comment by h4h13** [comment]
Does this helps we can implement 
https://pub.dev/packages/pattern_formatter
