### ISSUE TITLE
[Feature] Edit recurring events

### ISSUE THREAD

**Issue by DenisKnecht02** [h4h13/Paisa#400]
The current state of the app only allows deleting a recurring event. It is not possible to edit it. It would be great if you could edit the event (maybe with an option to change already created transactions or just the following transactions). In the current state, if for example your rent changes, you need to delete the current event and create a new one. With this feature, you only need to change the amount.

**Comment by yolocusharma** [comment]
"Recurring events", "Debit" and "Credit" do not get exported. Please consider that as well as of this feature request.

**Comment by DrakeChao** [comment]
I am shocked, why it isnt a thing by default 🤦‍♂️ who wants it to recur indefinitely. Please add the option to edit recurring events, please 🙏
And are we going to get confirmation about when its going to be worked on?

**Comment by dhruvanbhalara** [comment]
Similar to #321
