### ISSUE TITLE
Add forecast

### ISSUE THREAD

**Issue by Myzel394** [h4h13/Paisa#403]
Add a forecast graph to estimate how much you will be spending in each category

**Comment by h4h13** [comment]
Hey, Can you elaborate more please

**Comment by Myzel394** [comment]
Like let's say I got the following spending habits:

* Januar 2024: $100 in food
* February 2024: $120 in food
* March 2024: $140 in food
* April 2024: $160 in food

based on these values, I'd probably spend $180 in food in May 2024. It'd be very cool if we could have a graph that shows old spendings plus a forecast. Afaik this can be implemented using simple maths and without like a huge AI model or something like that :D

**Comment by h4h13** [comment]
Hey sorry for delay can you help with any app that doing this will help understanding better

**Comment by h4h13** [comment]
This will be overkill for me can't do it
