### ISSUE TITLE
Add API to post or synch data to the backend like odoo community

### ISSUE THREAD

**Issue by Ujeeee** [h4h13/Paisa#404]
Hi, love this app, it will be really great if it can connect to self hosted backend.

**Comment by bigolewannabe** [comment]
A first pass might be the ability to write data to general storage (ie documents) and then detect when that file changes. When that happens reload the app or minimally indicate it won't write until restarted/refreshed. Sync services like nextcloud and synching can take care of the rest.

**Comment by h4h13** [comment]
Hey, for now Paisa is completely local hence closing this issue
