### ISSUE TITLE
[Feature Request] Showing the total income and expense for each month/range in the home/overview

### ISSUE THREAD

**Issue by Rafee-M** [h4h13/Paisa#438]
### Home:
The home menu currently displays the total income and expense for the current month. I think it would be useful if we could click on it and it could show us a new window.
![Screenshot_2024-03-02-12-12-37-24_4ca28f6827a5efdcf85a7e5ffee4dda7_1](https://github.com/RetroMusicPlayer/Paisa/assets/69535896/16d073b3-1286-4ae4-bca6-8b261472afff)

**How the window would work:** We could select the year and it would show us the total income/expense data for the year at the top and the income/expense data for it's months below.

### Overview menu:
The ability see the data for a specific range is really useful and I love it! A small suggestion would be to add the total income and expense for that specific range above the categories
![Screenshot_2024-03-02-12-29-01-58_4ca28f6827a5efdcf85a7e5ffee4dda7_1](https://github.com/RetroMusicPlayer/Paisa/assets/69535896/8612070c-32f8-4a3b-9d5b-4e25ae669ae7)

**Comment by h4h13** [comment]
We can fix both of the request if we total in overview page
