### ISSUE TITLE
Laggy and choppy app experience 

### ISSUE THREAD

**Issue by nisabmohd** [h4h13/Paisa#450]
I'm currently using version 6.0.6 and find too many issues feels very laggy when used

**Comment by VarunS2002** [comment]
Same here, do you have many transactions added (like more than a hundred)?

**Comment by nisabmohd** [comment]
Yes

**Comment by jaredkz** [comment]
The cause of the issue has been identified and a fix is in development. It has to do with the way the app deals with larger amounts of transactions.

**Comment by h4h13** [comment]
Hey this is fixed closing it
