### ISSUE TITLE
Support to import part transaction

### ISSUE THREAD

**Issue by AD-ZERO** [h4h13/Paisa#456]
Currently when we import json , old data get's deleted and new data is added, can't we not delete old transaction and just add/update the data, we can add new feature to delete all data if user want to

**Comment by h4h13** [comment]
Why do we delete old entries  is when add new entry to local data base it assigns new id for each item this will be not reset until the app is uninstalled so we have to delete everything and add new data

**Comment by AD-ZERO** [comment]
So rather than update, could team provide the feature of adding new entries in bulk through json import and keep the old entries as it is.

**Comment by h4h13** [comment]
the number for each transaction is reset every time we restore
