### ISSUE TITLE
Accounts with different currencies

### ISSUE THREAD

**Issue by tothpsk** [h4h13/Paisa#479]
The app is almost perfect. What I miss are accounts with different currencies. For example, having account A with euros, account B with CZK and being able to make transfers between them. 
Thank you so much for consideration and congrats for beautiful app. 

Peter

**Comment by h4h13** [comment]
Hey, we're not doing this hence closing this

**Comment by h4h13** [comment]
Check this #457

**Comment by tothpsk** [comment]
Thanks. I can understand it is a bit of work, but it is doable. For example [Homebank](http://homebank.free.fr/) supports multiple currencies and it works well
