### ISSUE TITLE
Transfer shows in income 

### ISSUE THREAD

**Issue by NekoMimiOfficial** [h4h13/Paisa#481]
The current behavior of transfers is creating an income on the destination and an expense on the source,
This would work fine but it shows in the main income amount and line, if possible an option where this can be disabled would be appreciated

**Comment by suhan-paradkar** [comment]
It also changes the graph as well...  Now that's unintuitive

**Comment by validusername19** [comment]
See #490

**Comment by h4h13** [comment]
hey, new updates has new transaction category 
Transfer items shows as transfer instead of income and expense
