### ISSUE TITLE
Paying debts not working

### ISSUE THREAD

**Issue by NekoMimiOfficial** [h4h13/Paisa#482]
Trying to pay a debt or a credit will simply do nothing
A date is picked and an amount is set but no change happens when the update button is pressed

**Comment by Noopss** [comment]
Same here, CalyxOS 5.8.0 on a Pixel 8a

**Comment by dev-leom** [comment]
Same issue (cupid hyper os Xiaomi.eu ROM)

**Comment by h4h13** [comment]
This is fixed in v6.1.7 please check and reopen this issue
