### ISSUE TITLE
Is it possible to donate to this project?

### ISSUE THREAD

**Issue by MMachado05** [h4h13/Paisa#483]
I'm likely breaking standard Issue-making etiquette here, but as I don't have any way to contact devs, I figured I'd use the only option available to me and take on the risk of committing a faux pas!

Pretty much just as it says on the tin. I love the idea of F/LOSS being expanded and normalized, but to do so requires capital. Is there any way to support the development of this project monetarily? Be it through GitHub sponsors, Patreon, OpenCollective, etc?

**Comment by coutnoah** [comment]
Seems like the creator has a link here to support him, but not for the project as a whole: https://www.buymeacoffee.com/h4h13

It's in the settings page and I found it in the code here:
https://github.com/h4h13/Paisa/blob/863a649bbe3594fc46e841a502b450e74501535b/lib/core/constants/constants.dart#L34

**Comment by MMachado05** [comment]
Right you are! I'll take a note of it. 😊
