### ISSUE TITLE
Add Change Language Option in Settings Screen

### ISSUE THREAD

**Issue by Scienticious** [h4h13/Paisa#500]
When we have localization files, where can we change app language?

I have installed the app but haven't found an option to change the language.

**Comment by PrestigiousBeat6355** [comment]
It's available in setting for Android. Which Platform you are using?

**Comment by h4h13** [comment]
@Scienticious is this issue fixed closing for now

**Comment by Scienticious** [comment]
I want to explicitly change the language settings of the app.
Is this option is available?
Also, my device settings are in German, but when I open the app , it is English.

What I am doing wrong?

**Comment by PrestigiousBeat6355** [comment]
I think the app isn't detecting device language,but option to change language manually is available in settings.
