### ISSUE TITLE
[Play Store][Android 9]: Available version not updated still 6.0.6 

### ISSUE THREAD

**Issue by rahulkhatri137** [h4h13/Paisa#504]
Version available on Play Store is still 6.0.6 updated on Mar 6 2024 and not updated to the latest as on GitHub for Android 9.

**Comment by dombroks** [comment]
@h4h13

**Comment by h4h13** [comment]
v6.1.5 has released to play store

**Comment by rahulkhatri137** [comment]
> v6.1.5 has released to play store

Is the signature of Play Store version and GitHub release different as update from Play Store failed?

![IMG_20240701_212451](https://github.com/h4h13/Paisa/assets/82636553/7c2e1998-c7c7-4db2-a84a-7fb45165878b)
