### ISSUE TITLE
[Feature Request] Widget for the Accounts

### ISSUE THREAD

**Issue by archziac** [h4h13/Paisa#505]
Add widgets to put on the homescreen for the accounts section for the cards like stuff
![Screenshot_20240702-003451](https://github.com/h4h13/Paisa/assets/96952929/9e9b5a38-02a0-44bc-a5b0-d37b214cda6d)

**Comment by Rajala1404** [comment]
That would actually be nice

**Comment by h4h13** [comment]
Hey we have one right now not releated to account but related to total summary check it out

**Comment by h4h13** [comment]
For now closing this issue
