### ISSUE TITLE
All data overwritten with example data

### ISSUE THREAD

**Issue by JnkLtt** [h4h13/Paisa#510]
After updating to 6.1.7 all of my accounts, expenses and categories are gone and have been replaced by placeholders or something like that.
![Screenshot_20240705_173429_Paisa](https://github.com/h4h13/Paisa/assets/93495035/149fc118-e0d1-4b96-a820-99330e89979c)
Interestingly enough it still welcomes me back with my name.

**Comment by Mischievous-Loner** [comment]
Happened with me too, I should have opened GitHub before updating

**Comment by kugel89** [comment]
Same here, all data collected for months is gone. Awesome

**Comment by chrostino** [comment]
same here

**Comment by dev-leom** [comment]
Same 🥲. Please tell me it's recoverable.

**Comment by SpezialK-dev** [comment]
I am afraid of looking at the code, that nothing is recoverable, and I would advise against putting in data because if you force restart the app, all of it will be replaced again with dummy data.

https://github.com/h4h13/Paisa/commit/4f722b11aced7b5e5710abb87b5424301bd30757 This commit introduced dummy data generation into main, but there are no checks if the dummy data has been previously created or not. Nor is there a check for other data, so every time the properly starts, it will reset everything. Also, dummy data seems to just wipe all the previous data.

**Comment by FosRexx** [comment]
Guys, after the new update I am now 1.7 million in debt. I don't have that much money and I don't know how I got that much debt, looking into the transaction history it seems like the debt was due to my spending habits but, I promise I have not spent that much. Please help me, I need to somehow pay my debt. If you can spare a few changes please feel free to donate me [here]()https://youtu.be/dQw4w9WgXcQ.

![Screenshot_20240706-143230_Paisa_1.png](https://github.com/h4h13/Paisa/assets/105154048/47e58043-55e3-4dca-bf26-a63c8dea7ea7)

**Comment by h4h13** [comment]
Hey, sorry guys please check v.6.1.8 delete or import old backup to fix

**Comment by chrostino** [comment]
> Hey, sorry guys please check v.6.1.8 delete or import old backup to fix

is it on fdroid already?

**Comment by JnkLtt** [comment]
> Hey, sorry guys please check v.6.1.8 delete or import old backup to fix

Thanks for the quick fix. Shame that the data couldn't be recovered although I didn't really expect that.

**Comment by dev-leom** [comment]
> Hey, sorry guys please check v.6.1.8 delete or import old backup to fix

Unable to import the backup made just before the v6.1.7 update. But v6.1.8 Stop adding false data 👍

**Comment by h4h13** [comment]
> > Hey, sorry guys please check v.6.1.8 delete or import old backup to fix
> 
> Unable to import the backup made just before the v6.1.7 update. But v6.1.8 Stop adding false data 👍

Can you share logs or any crash happening will try to fix

**Comment by timechips** [comment]
Happened the same here:
- [x] ![Screenshot_20240708-105041.png](https://github.com/h4h13/Paisa/assets/170237734/510b90ab-5568-499b-9fdb-900504127ca2)

![Screenshot_20240708-104157.png](https://github.com/h4h13/Paisa/assets/170237734/180f9256-cf17-4436-a50d-3f89041109bd)

![Screenshot_20240708-105038.png](https://github.com/h4h13/Paisa/assets/170237734/ff9870ec-7b6e-47d1-9832-90f248def703)

These are the very short app logs:
```
type: logcat
osVersion: google/shiba/shiba:14/AP2A.240705.005/2024070201:user/release-keys
packageName: dev.hemanths.paisa:617
buffers: main,system,crash,events,kernel
level: verbose

```
And system logs:
```
type: logcat
osVersion: google/shiba/shiba:14/AP2A.240705.005/2024070201:user/release-keys
packageName: dev.hemanths.paisa:617
buffers: main,system,crash,events,kernel
level: verbose

--------- beginning of events
07-08 08:52:30.646 11770 11770 I wm_on_restart_called: [Token=226251210,Component Name=dev.hemanths.paisa.MainActivity,Reason=performRestart,time=0ms]
07-08 08:52:30.647 11770 11770 I viewroot_draw_event: [window=VRI[MainActivity],event=applyTransactionOnDraw applyImmediately]
07-08 08:52:30.647 11770 11770 I wm_on_start_called: [Token=226251210,Component Name=dev.hemanths.paisa.MainActivity,Reason=handleStartActivity,time=1ms]
07-08 08:52:30.651 11770 11770 I wm_on_resume_called: [Token=226251210,Component Name=dev.hemanths.paisa.MainActivity,Reason=RESUME_ACTIVITY,time=0ms]
07-08 08:52:30.652 11770 11770 I wm_on_top_resumed_gained_called: [Token=226251210,Component Name=dev.hemanths.paisa.MainActivity,Reason=topWhenResuming]
07-08 08:52:30.653 11770 11770 I viewroot_draw_event: [window=VRI[MainActivity],event=applyTransactionOnDraw applyImmediately]
07-08 08:52:30.663 11770 11770 I viewroot_draw_event: [window=VRI[MainActivity],event=Start draw after previous draw not visible]
07-08 08:52:30.686 11770 11770 I viewroot_draw_event: [window=VRI[MainActivity],event=reportDrawFinished seqId=0]
07-08 08:53:19.389 11770 11770 I wm_on_top_resumed_lost_called: [Token=226251210,Component Name=dev.hemanths.paisa.MainActivity,Reason=topStateChangedWhenResumed]
07-08 08:53:19.433 11770 11770 I view_enqueue_input_event: [eventType=Motion - Cancel,action=dev.hemanths.paisa/dev.hemanths.paisa.MainActivity]
07-08 08:53:20.186 11770 11770 I wm_on_paused_called: [Token=226251210,Component Name=dev.hemanths.paisa.MainActivity,Reason=performPause,time=1ms]
07-08 08:53:20.220 11770 11770 I wm_on_stop_called: [Token=226251210,Component Name=dev.hemanths.paisa.MainActivity,Reason=STOP_ACTIVITY_ITEM,time=2ms]
07-08 08:53:20.663 11770 11770 I wm_on_destroy_called: [Token=226251210,Component Name=dev.hemanths.paisa.MainActivity,Reason=performDestroy,time=434ms]
```

**Comment by h4h13** [comment]
Hey, sorry everyone even my data is overriten by this mistake I have remove this test data completly this will not repeat again
If there is any other issue please raise as another ticket

**Comment by h4h13** [comment]
Since no further comments will close this for now
