### ISSUE TITLE
[Bug] Debt/Credit not updating with Pay option!

### ISSUE THREAD

**Issue by rahulkhatri137** [h4h13/Paisa#514]
Amount of Debt/Credit doesn't update after paying. It's stuck at same amount no pay transaction is registered on progress bar too

**Comment by bithst** [comment]
Facing this same issue as well. Paid transactions are not being registered.

**Comment by h4h13** [comment]
Hey, are you selecting the date while adding the amount

**Comment by rahulkhatri137** [comment]
> Hey, are you selecting the date while adding the amount

Yes Date already selected, also if date is not selected then it doesn't accept the transaction while issue is transaction is accepted but is not registered in the progress.

**Comment by h4h13** [comment]
Can you make a video of it please

**Comment by rahulkhatri137** [comment]
Closing as bug is not reproduced on v6.2.1 (latest available on PlayStore)
