### ISSUE TITLE
Bring back Monthly Total in the same row of the dates or months.

### ISSUE THREAD

**Issue by zahidshaikh08** [h4h13/Paisa#516]
In the latest 6.2.3 the monthly total of the transactions has been removed, can we please bring back it??

It was very essential and good insights for the user's to get overview of total amount of expenses in a month or on a particular date.

It was there in the previous versions but in the latest version it has been removed.

![image](https://github.com/h4h13/Paisa/assets/59495361/f2fe3ba0-7879-4fad-b33f-a58832bdc6be)

**Comment by h4h13** [comment]
Yes this is little diffcult now to do it
