### ISSUE TITLE
Adding support for having multiple currencies

### ISSUE THREAD

**Issue by Masrkai** [h4h13/Paisa#526]
This is not an issue but rather a feature request i don't know where else to put it so i put it here in the issue tracker

So if we have an **_account A_** with specific region currency say **_pounds_**  and _**account B**_  with other currency say **_Canadian dollars_**

It's not really beneficial to have one currency system across the entire application and in real world 3rd class countries they have other currencies as a _"very high demanding object"_ to secure them financially or their jobs and possibilities of other use cases are endless
 
- //my English is betraying me at this point to just demonstrate foreign currencies are dealt with sometimes just like gold 

And I am sorry for raising this issue without a logical solution while being a programmer myself but i hope someone can and will be able to put a solution for this that is better than just "profiles" kind of management

**Comment by h4h13** [comment]
Check this https://github.com/h4h13/Paisa/issues/457
