### ISSUE TITLE
Feature request: adding transaction via intent

### ISSUE THREAD

**Issue by astroanax** [h4h13/Paisa#532]
Namaste sir, nim app tumba olle ide, aadare ond issue ide.

I think the app's functionality could be improved if we could add a transaction via an intent, instead of opening the app and clicking buttons. This way the app could be used in conjunction with an automation app like Tasker to automatically add a transaction, either via some trigger (like UPI SMS notification) or maybe double tapping the back of your phone.

**Comment by h4h13** [comment]
Hey, we don't read SMS anything in regards to it because of privacy issues
hence closing this issue

**Comment by astroanax** [comment]
You did not understand what I meant at all - I am not asking for Paisa to read SMS notifications, no. I asked for support to add transactions via an intent and merely gave an example that Tasker could read SMS and add a transaction.
